import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Create a sample dataset
sample_size = 500
data = {
    'CustomerID': np.random.randint(1000, 2000, sample_size),
    'Gender': np.random.choice(['Male', 'Female'], sample_size),
    'Age': np.random.randint(18, 60, sample_size),
    'ProductCategory': np.random.choice(['Grocery', 'Clothing', 'Electronics', 'Cosmetics'], sample_size),
    'PurchaseAmount': np.round(np.random.normal(500, 150, sample_size), 2),
    'PurchaseDate': pd.date_range(start='2024-01-01', periods=sample_size, freq='D')
}

df = pd.DataFrame(data)

# Step 2: Basic Exploration
print("\nFirst 5 Rows:")
print(df.head())
print("\nDescription:")
print(df.describe()) 
print("\nInfo:")
(df.info())

# Step 3: Customer Age Distribution
plt.figure(figsize=(8, 4))
sns.histplot(df['Age'], kde=True, bins=10, color='skyblue')
plt.title('Customer Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# Step 4: Gender-Based Spending
plt.figure(figsize=(6, 4))
sns.boxplot(x='Gender', y='PurchaseAmount', data=df)
plt.title('Purchase Amount by Gender')
plt.tight_layout()
plt.show()

# Step 5: Product Category Preference
plt.figure(figsize=(8, 4))
sns.countplot(data=df, x='ProductCategory', order=df['ProductCategory'].value_counts().index, palette='viridis')
plt.title('Product Category Preference')
plt.xlabel('Category')
plt.ylabel('Number of Purchases')
plt.tight_layout()
plt.show()

# Step 6: Revenue per Product Category
category_revenue = df.groupby('ProductCategory')['PurchaseAmount'].sum().sort_values(ascending=False)
category_revenue.plot(kind='bar', color='orange', figsize=(8, 4))
plt.title('Total Revenue by Product Category')
plt.ylabel('Revenue')
plt.tight_layout()
plt.show()

# Step 7: Monthly Revenue Trend
df['Month'] = df['PurchaseDate'].dt.to_period('M')
monthly_revenue = df.groupby('Month')['PurchaseAmount'].sum()

monthly_revenue.plot(marker='o', figsize=(10, 5))
plt.title('Monthly Revenue Trend')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.grid(True)
plt.tight_layout()
plt.show()

Step 8: High-Value Customer
top_customers = df.groupby('CustomerID')['PurchaseAmount'].sum().sort_values(ascending=False).head(10)


# # HERE ARE THE KEY INSIGHTS FROM THE CODE IN PROJECT DEPARTMENTAL STORE:

# Synthetic Dataset Creation:
# A sample dataset of 500 customers is generated, each with CustomerID, Gender, Age, ProductCategory, PurchaseAmount, and PurchaseDate.
# Product categories include Grocery, Clothing, Electronics, and Cosmetics.
# Data Exploration:
# The dataset is explored with .head(), .describe(), and .info() to understand its structure, statistics, and data types.
# Customer Age Distribution:
# The age of customers ranges from 18 to 60.
# The age distribution is visualized with a histogram, helping identify the most common customer age groups.
# Gender-Based Spending:
# Purchase amounts are compared between Male and Female customers using a boxplot.
#This highlights differences or similarities in spending behavior by gender.
# Product Category Preference:
# A countplot shows which product categories are most frequently purchased.
#Reveals customer preferences for certain categories in the departmental store.
# Revenue per Product Category:
# The total revenue generated by each product category is calculated and visualized.
 #This helps identify which categories are most profitable.
# Monthly Revenue Trend:
# Revenue is grouped by month and plotted to show sales trends over time.
# Useful to detect seasonality or growth patterns.
# High-Value Customers:
# The top 10 customers, by total spend, are identified and visualized.
#Helps in targeting and rewarding loyal/high-spending customers.
# top_customers.plot(kind='bar', color='green', figsize=(8, 4))
#plt.title('Top 10 High-Value Customers')
#plt.ylabel('Total Spend')
#plt.tight_layout()
# plt.show()




